STARTCOMMENT

STARTVERSION
1.0
# 1. Lines starting with a # are comments.
# 2. No line may be longer than 250 bytes. As this file is UTF-8 encoded,
#    characters above U+007F take up 2 or more bytes.
# 3. If a line exceeds 250 characters, add the text "\n", without quotes,
#    then a newline. You may continue the text on the next line.
# 4. See the comment line ABOVE a message for its context. For example:
#  > #MSG_MAIN_MENU_SAVED_STATES
#  > Saved states
ENDVERSION

ENDCOMMENT

STARTENGLISH
#MSG_MAIN_MENU_COMPRESS
Compress
#MSG_MAIN_MENU_DECOMPRESS
Decompress
#MSG_MAIN_MENU_OPTIONS
Options
#MSG_MAIN_MENU_EXIT
Exit
#FMT_OPTIONS_LANGUAGE
Language                          %s
#MSG_OPTIONS_CARD_CAPACITY
Card capacity
#MSG_OPTIONS_RESET
Restore default settings
#MSG_OPTIONS_VERSION
Version information
#MSG_GENERAL_OFF
Off
#MSG_GENERAL_ON
On
#MSG_GENERAL_CONFIRM_WITH_A
[A] Confirm
#MSG_GENERAL_CANCEL_WITH_B
[B] Cancel
#MSG_CHANGE_LANGUAGE
Changing language...
#MSG_CHANGE_LANGUAGE_WAITING
Please wait...
#MSG_APPLICATION_NAME
DS2Compress gzip file handler
#MSG_WORD_APPLICATION_VERSION
Version
#MSG_DIALOG_RESET
Reset all settings to defaults?
#MSG_PROGRESS_RESETTING
Please wait...
#MSG_DIALOG_OVERWRITE_EXISTING_FILE
The destination file already exists. Do you wish to overwrite it?
#MSG_FILE_OVERWRITE_WITH_A
[A] Overwrite
#MSG_FILE_LEAVE_WITH_B
[B] Leave
#MSG_PROGRESS_COMPRESSING
Compressing...
#MSG_PROGRESS_DECOMPRESSING
Decompressing...
#MSG_ERROR_INPUT_FILE_READ
Failed to read some of the input file. Check that the storage card is properly secured.
#MSG_ERROR_COMPRESSED_FILE_READ
Failed to read some of the compressed file. It may be corrupt. Also check that the storage card is properly secured.
#MSG_ERROR_OUTPUT_FILE_OPEN
Failed to create the destination file. Either the storage card doesn't have enough free space, the file exists as a directory, its name is too long or the root directory has 512 items.
#MSG_ERROR_OUTPUT_FILE_WRITE
Failed to completely write the destination file. Check that the storage card is properly secured and that it has enough free space.
#MSG_ERROR_RETRY_WITH_A
[A] Retry
#MSG_ERROR_ABORT_WITH_B
[B] Abort

ENDENGLISH
